version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/blog
    ports:
      - "8300:3000"
  pgsql:
    image: postgres:14-alpine
    volumes:
      - 'database:/var/lib/postgresql/data'
    ports:
      - "8432:5432"
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: redis:6-alpine
volumes:
  database: